// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.ViewModels;
// this will be used to create reports that uses the employees data
public partial class EmployeeViewModel
{
  
    public int Id { get; set; }

  
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Gender { get; set; }

    public string Email { get; set; }


    public int Salary { get; set; }

    public string EmploymentType { get; set; }

    public string JobTitle { get; set; }

    public string JobType { get; set; }



    public string WorkingModel { get; set; }
  

   

    

}