// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("AuditObject")]
[Index("ObjectName", Name = "IX_AuditObject")]
public partial class AuditObject
{
    [Key]
    public int AuditObjectId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ObjectName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ObjectFullyQualifiedName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("AuditObject")]
    public virtual ICollection<AuditObjectProperty> AuditObjectProperties { get; set; } = new List<AuditObjectProperty>();
}