// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("AuditObjectProperty")]
[Index("AuditObjectId", "PropertyName", Name = "IX_AuditObjectProperty")]
public partial class AuditObjectProperty
{
    [Key]
    public int AuditObjectPropertyId { get; set; }

    public int AuditObjectId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string PropertyName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("AuditObjectId")]
    [InverseProperty("AuditObjectProperties")]
    public virtual AuditObject AuditObject { get; set; }
}