// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("Audit")]
public partial class Audit
{
    [Key]
    public int AuditId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ObjectName { get; set; }

    public int RecordId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PropertyName { get; set; }

    [Unicode(false)]
    public string OldValue { get; set; }

    [Unicode(false)]
    public string NewValue { get; set; }

    public byte AuditType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }
}