// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("Capability")]
[Index("CapabilityName", Name = "IX_Capability", IsUnique = true)]
public partial class Capability
{
    [Key]
    public int CapabilityId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CapabilityName { get; set; }

    public int? MenuItemId { get; set; }

    public byte AccessType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("MenuItemId")]
    [InverseProperty("Capabilities")]
    public virtual MenuItem MenuItem { get; set; }

    [InverseProperty("Capability")]
    public virtual ICollection<RoleCapability> RoleCapabilities { get; set; } = new List<RoleCapability>();
}