// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("Email")]
public partial class Email
{
    [Key]
    public int EmailId { get; set; }

    [Required]
    [Unicode(false)]
    public string ToEmailAddress { get; set; }

    [Unicode(false)]
    public string CCEmailAddress { get; set; }

    [Unicode(false)]
    public string BCCEmailAddress { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string FromEmailAddress { get; set; }

    [Required]
    [Unicode(false)]
    public string Subject { get; set; }

    [Required]
    [Unicode(false)]
    public string Body { get; set; }

    public byte EmailStatusFlag { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }
}