// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("Holiday")]
[Index("HolidayDate", Name = "IX_Holiday", IsUnique = true)]
public partial class Holiday
{
    [Key]
    public int HolidayId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string HolidayName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime HolidayDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }
}