// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("MenuItem")]
[Index("MenuItemName", Name = "IX_MenuItem", IsUnique = true)]
public partial class MenuItem
{
    [Key]
    public int MenuItemId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string MenuItemName { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    [Unicode(false)]
    public string Url { get; set; }

    public int? ParentMenuItemId { get; set; }

    public byte DisplaySequence { get; set; }

    public bool IsAlwaysEnabled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("MenuItem")]
    public virtual ICollection<Capability> Capabilities { get; set; } = new List<Capability>();

    [InverseProperty("ParentMenuItem")]
    public virtual ICollection<MenuItem> InverseParentMenuItem { get; set; } = new List<MenuItem>();

    [ForeignKey("ParentMenuItemId")]
    [InverseProperty("InverseParentMenuItem")]
    public virtual MenuItem ParentMenuItem { get; set; }
}