// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("NotificationUserAccount")]
public partial class NotificationUserAccount
{
    [Key]
    public int NotificationUserAccountId { get; set; }

    public int NotificationId { get; set; }

    public int UserAccountId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("NotificationId")]
    [InverseProperty("NotificationUserAccounts")]
    public virtual Notification Notification { get; set; }

    [InverseProperty("NotificationUserAccount")]
    public virtual ICollection<NotificationWorkFlowState> NotificationWorkFlowStates { get; set; } = new List<NotificationWorkFlowState>();

    [ForeignKey("UserAccountId")]
    [InverseProperty("NotificationUserAccounts")]
    public virtual UserAccount UserAccount { get; set; }
}