// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("Notification")]
public partial class Notification
{
    [Key]
    public int NotificationId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string FromEmailAddress { get; set; }

    [Required]
    [Unicode(false)]
    public string Subject { get; set; }

    [Required]
    [Unicode(false)]
    public string Body { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("Notification")]
    public virtual ICollection<NotificationUserAccount> NotificationUserAccounts { get; set; } = new List<NotificationUserAccount>();
}