// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("NotificationWorkFlowState")]
public partial class NotificationWorkFlowState
{
    [Key]
    public int NotificationWorkFlowStateId { get; set; }

    public int NotificationUserAccountId { get; set; }

    public int WorkFlowStateId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("NotificationUserAccountId")]
    [InverseProperty("NotificationWorkFlowStates")]
    public virtual NotificationUserAccount NotificationUserAccount { get; set; }

    [ForeignKey("WorkFlowStateId")]
    [InverseProperty("NotificationWorkFlowStates")]
    public virtual WorkFlowState WorkFlowState { get; set; }
}