// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class PaidTimeOffRequestSelectByUserAccountIdYearResult
    {
        public object CountOfFullVacation { get; set; }
        public object CountOfHalfVacation { get; set; }
        public object CountOfFullPersonal { get; set; }
        public object CountOfHalfPersonal { get; set; }
        public object CountOfFullUnpaid { get; set; }
        public object CountOfHalfUnPaid { get; set; }
    }
}
