// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("PaidTimeOffDayType")]
[Index("PaidTimeOffDayTypeName", Name = "IX_PaidTimeOffDayType")]
public partial class PaidTimeOffDayType
{
    [Key]
    public int PaidTimeOffDayTypeId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PaidTimeOffDayTypeName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("PaidTimeOffDayType")]
    public virtual ICollection<PaidTimeOffRequest> PaidTimeOffRequests { get; set; } = new List<PaidTimeOffRequest>();
}