// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class PaidTimeOffVacationBankSelectByUserAccountIdYearResult
    {
        public int PaidTimeOffVacationBankId { get; set; }
        public int UserAccountId { get; set; }
        public short VacationYear { get; set; }
        public byte PersonalDays { get; set; }
        public byte VacationDays { get; set; }
        public DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public DateTime Updated { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
        public object UserName { get; set; }
    }
}
