// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("PaidTimeOffVacationBank")]
[Index("UserAccountId", "VacationYear", Name = "IX_PaidTimeOffVacationBank")]
public partial class PaidTimeOffVacationBank
{
    [Key]
    public int PaidTimeOffVacationBankId { get; set; }

    public int UserAccountId { get; set; }

    public short VacationYear { get; set; }

    public byte PersonalDays { get; set; }

    public byte VacationDays { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("UserAccountId")]
    [InverseProperty("PaidTimeOffVacationBanks")]
    public virtual UserAccount UserAccount { get; set; }
}