// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("PaidTimeOffRequest")]
public partial class PaidTimeOffRequest
{
    [Key]
    public int PaidTimeOffRequestId { get; set; }

    public int UserAccountId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RequestDate { get; set; }

    public int PaidTimeOffDayTypeId { get; set; }

    public int PaidTimeOffRequestTypeId { get; set; }

    public bool Cancelled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("PaidTimeOffDayTypeId")]
    [InverseProperty("PaidTimeOffRequests")]
    public virtual PaidTimeOffDayType PaidTimeOffDayType { get; set; }

    [ForeignKey("PaidTimeOffRequestTypeId")]
    [InverseProperty("PaidTimeOffRequests")]
    public virtual PaidTimeOffRequestType PaidTimeOffRequestType { get; set; }

    [ForeignKey("UserAccountId")]
    [InverseProperty("PaidTimeOffRequests")]
    public virtual UserAccount UserAccount { get; set; }
}