// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class Report_RoleCapabilityResult
    {
        public string RoleName { get; set; }
        public byte AccessFlag { get; set; }
        public string CapabilityName { get; set; }
    }
}
