// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("Report")]
public partial class Report
{
    [Key]
    public int ReportId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ReportName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string FileName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ObjectName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string SubReportObjectName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SubReportMethodName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }
}