// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class ReportRoleUserAccountResult
    {
        public string RoleName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
