// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("RoleCapability")]
[Index("RoleId", "CapabilityId", Name = "IX_RoleCapability", IsUnique = true)]
public partial class RoleCapability
{
    [Key]
    public int RoleCapabilityId { get; set; }

    public int RoleId { get; set; }

    public int CapabilityId { get; set; }

    public byte AccessFlag { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("CapabilityId")]
    [InverseProperty("RoleCapabilities")]
    public virtual Capability Capability { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("RoleCapabilities")]
    public virtual Role Role { get; set; }
}