// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("Role")]
[Index("RoleName", Name = "IX_Role", IsUnique = true)]
public partial class Role
{
    [Key]
    public int RoleId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RoleCapability> RoleCapabilities { get; set; } = new List<RoleCapability>();

    [InverseProperty("Role")]
    public virtual ICollection<RoleUserAccount> RoleUserAccounts { get; set; } = new List<RoleUserAccount>();
}