// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("RoleUserAccount")]
[Index("RoleId", "UserAccountId", Name = "IX_RoleUserAccount", IsUnique = true)]
public partial class RoleUserAccount
{
    [Key]
    public int RoleUserAccountId { get; set; }

    public int RoleId { get; set; }

    public int UserAccountId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("RoleUserAccounts")]
    public virtual Role Role { get; set; }

    [ForeignKey("UserAccountId")]
    [InverseProperty("RoleUserAccounts")]
    public virtual UserAccount UserAccount { get; set; }
}