// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("UserAccount")]
[Index("AccountName", Name = "IX_UserAccount", IsUnique = true)]
public partial class UserAccount
{
    [Key]
    public int UserAccountId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string AccountName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("UserAccount")]
    public virtual ICollection<NotificationUserAccount> NotificationUserAccounts { get; set; } = new List<NotificationUserAccount>();

    [InverseProperty("UserAccount")]
    public virtual ICollection<PaidTimeOffRequest> PaidTimeOffRequests { get; set; } = new List<PaidTimeOffRequest>();

    [InverseProperty("UserAccount")]
    public virtual ICollection<PaidTimeOffVacationBank> PaidTimeOffVacationBanks { get; set; } = new List<PaidTimeOffVacationBank>();

    [InverseProperty("UserAccount")]
    public virtual ICollection<RoleUserAccount> RoleUserAccounts { get; set; } = new List<RoleUserAccount>();

    [InverseProperty("UserAccount")]
    public virtual ICollection<WorkFlowItemOwner> WorkFlowItemOwners { get; set; } = new List<WorkFlowItemOwner>();

    [InverseProperty("UserAccount")]
    public virtual ICollection<WorkFlowItemStateHistory> WorkFlowItemStateHistories { get; set; } = new List<WorkFlowItemStateHistory>();

    [InverseProperty("SubmitterUserAccount")]
    public virtual ICollection<WorkFlowItem> WorkFlowItems { get; set; } = new List<WorkFlowItem>();

    [InverseProperty("UserAccount")]
    public virtual ICollection<WorkFlowOwnerGroupUserAccount> WorkFlowOwnerGroupUserAccounts { get; set; } = new List<WorkFlowOwnerGroupUserAccount>();
}