// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("WorkFlowStateProperty")]
[Index("WorkFlowStateId", "PropertyName", Name = "IX_WorkFlowStateField", IsUnique = true)]
public partial class WorkFlowStateProperty
{
    [Key]
    public int WorkFlowStatePropertyId { get; set; }

    public int WorkFlowStateId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string PropertyName { get; set; }

    public bool Required { get; set; }

    public bool ReadOnly { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("WorkFlowStateId")]
    [InverseProperty("WorkFlowStateProperties")]
    public virtual WorkFlowState WorkFlowState { get; set; }
}