// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class WorkFlowOwnerGroupSelectByWorkFlowIdResult
    {
        public int WorkFlowOwnerGroupId { get; set; }
        public int WorkFlowId { get; set; }
        public string OwnerGroupName { get; set; }
        public int? DefaultUserAccountId { get; set; }
        public bool IsDefaultSameAsLast { get; set; }
        public string Description { get; set; }
        public DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public DateTime Updated { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
