// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class WorkFlowTransitionSelectAllResult
    {
        public int WorkFlowTransitionId { get; set; }
        public int WorkFlowId { get; set; }
        public string TransitionName { get; set; }
        public int? FromWorkFlowStateId { get; set; }
        public int ToWorkFlowStateId { get; set; }
        public string PostTransitionMethodName { get; set; }
        public DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public DateTime Updated { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
        public string FromStateName { get; set; }
        public string ToStateName { get; set; }
    }
}
