// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("WorkFlow")]
[Index("WorkflowName", Name = "IX_Workflow", IsUnique = true)]
public partial class WorkFlow
{
    [Key]
    public int WorkFlowId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string WorkflowName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string WorkFlowObjectName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("WorkFlow")]
    public virtual ICollection<WorkFlowItem> WorkFlowItems { get; set; } = new List<WorkFlowItem>();

    [InverseProperty("WorkFlow")]
    public virtual ICollection<WorkFlowState> WorkFlowStates { get; set; } = new List<WorkFlowState>();

    [InverseProperty("WorkFlow")]
    public virtual ICollection<WorkFlowTransition> WorkFlowTransitions { get; set; } = new List<WorkFlowTransition>();
}