// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("WorkFlowItemOwner")]
public partial class WorkFlowItemOwner
{
    [Key]
    public int WorkFlowItemOwnerId { get; set; }

    public int WorkFlowItemId { get; set; }

    public int WorkFlowOwnerGroupId { get; set; }

    public int? UserAccountId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("UserAccountId")]
    [InverseProperty("WorkFlowItemOwners")]
    public virtual UserAccount UserAccount { get; set; }

    [ForeignKey("WorkFlowItemId")]
    [InverseProperty("WorkFlowItemOwners")]
    public virtual WorkFlowItem WorkFlowItem { get; set; }

    [ForeignKey("WorkFlowOwnerGroupId")]
    [InverseProperty("WorkFlowItemOwners")]
    public virtual WorkFlowOwnerGroup WorkFlowOwnerGroup { get; set; }
}