// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("WorkFlowOwnerGroup")]
[Index("WorkFlowId", "OwnerGroupName", Name = "IX_WorkFlowOwnerGroup", IsUnique = true)]
public partial class WorkFlowOwnerGroup
{
    [Key]
    public int WorkFlowOwnerGroupId { get; set; }

    public int WorkFlowId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string OwnerGroupName { get; set; }

    public int? DefaultUserAccountId { get; set; }

    public bool IsDefaultSameAsLast { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("WorkFlowOwnerGroup")]
    public virtual ICollection<WorkFlowItemOwner> WorkFlowItemOwners { get; set; } = new List<WorkFlowItemOwner>();

    [InverseProperty("WorkFlowOwnerGroup")]
    public virtual ICollection<WorkFlowOwnerGroupUserAccount> WorkFlowOwnerGroupUserAccounts { get; set; } = new List<WorkFlowOwnerGroupUserAccount>();

    [InverseProperty("WorkFlowOwnerGroup")]
    public virtual ICollection<WorkFlowState> WorkFlowStates { get; set; } = new List<WorkFlowState>();
}