// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class WorkFlowStateSelectAllResult
    {
        public int WorkFlowStateId { get; set; }
        public int WorkFlowId { get; set; }
        public string StateName { get; set; }
        public string Description { get; set; }
        public int? WorkFlowOwnerGroupId { get; set; }
        public bool IsOwnerSubmitter { get; set; }
        public DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public DateTime Updated { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
