// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("WorkFlowTransition")]
[Index("FromWorkFlowStateId", "ToWorkFlowStateId", Name = "IX_WorkFlowTransition_1", IsUnique = true)]
public partial class WorkFlowTransition
{
    [Key]
    public int WorkFlowTransitionId { get; set; }

    public int WorkFlowId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TransitionName { get; set; }

    public int? FromWorkFlowStateId { get; set; }

    public int ToWorkFlowStateId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PostTransitionMethodName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("FromWorkFlowStateId")]
    [InverseProperty("WorkFlowTransitionFromWorkFlowStates")]
    public virtual WorkFlowState FromWorkFlowState { get; set; }

    [ForeignKey("ToWorkFlowStateId")]
    [InverseProperty("WorkFlowTransitionToWorkFlowStates")]
    public virtual WorkFlowState ToWorkFlowState { get; set; }

    [ForeignKey("WorkFlowId")]
    [InverseProperty("WorkFlowTransitions")]
    public virtual WorkFlow WorkFlow { get; set; }
}