// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("WorkFlowItemStateHistory")]
public partial class WorkFlowItemStateHistory
{
    [Key]
    public int WorkFlowItemStateHistoryId { get; set; }

    public int WorkFlowItemId { get; set; }

    public int WorkFlowStateId { get; set; }

    public int UserAccountId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("UserAccountId")]
    [InverseProperty("WorkFlowItemStateHistories")]
    public virtual UserAccount UserAccount { get; set; }

    [ForeignKey("WorkFlowItemId")]
    [InverseProperty("WorkFlowItemStateHistories")]
    public virtual WorkFlowItem WorkFlowItem { get; set; }

    [ForeignKey("WorkFlowStateId")]
    [InverseProperty("WorkFlowItemStateHistories")]
    public virtual WorkFlowState WorkFlowState { get; set; }
}