// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models2;

[Table("WorkFlowState")]
[Index("WorkFlowId", "StateName", Name = "IX_WorkFlowState", IsUnique = true)]
public partial class WorkFlowState
{
    [Key]
    public int WorkFlowStateId { get; set; }

    public int WorkFlowId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string StateName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    public int? WorkFlowOwnerGroupId { get; set; }

    public bool IsOwnerSubmitter { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [InverseProperty("WorkFlowState")]
    public virtual ICollection<NotificationWorkFlowState> NotificationWorkFlowStates { get; set; } = new List<NotificationWorkFlowState>();

    [ForeignKey("WorkFlowId")]
    [InverseProperty("WorkFlowStates")]
    public virtual WorkFlow WorkFlow { get; set; }

    [InverseProperty("WorkFlowState")]
    public virtual ICollection<WorkFlowItemStateHistory> WorkFlowItemStateHistories { get; set; } = new List<WorkFlowItemStateHistory>();

    [ForeignKey("WorkFlowOwnerGroupId")]
    [InverseProperty("WorkFlowStates")]
    public virtual WorkFlowOwnerGroup WorkFlowOwnerGroup { get; set; }

    [InverseProperty("WorkFlowState")]
    public virtual ICollection<WorkFlowStateProperty> WorkFlowStateProperties { get; set; } = new List<WorkFlowStateProperty>();

    [InverseProperty("FromWorkFlowState")]
    public virtual ICollection<WorkFlowTransition> WorkFlowTransitionFromWorkFlowStates { get; set; } = new List<WorkFlowTransition>();

    [InverseProperty("ToWorkFlowState")]
    public virtual ICollection<WorkFlowTransition> WorkFlowTransitionToWorkFlowStates { get; set; } = new List<WorkFlowTransition>();
}