// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Reflections.Nexus.Shared.Models2
{
    public partial class WorkFlowItemStateHistorySelectAllResult
    {
        public int WorkFlowItemStateHistoryId { get; set; }
        public int WorkFlowItemId { get; set; }
        public int WorkFlowStateId { get; set; }
        public int UserAccountId { get; set; }
        public DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public DateTime Updated { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] RowVersion { get; set; }
        public string StateName { get; set; }
        public object OwnerName { get; set; }
        public object InsertedBy { get; set; }
    }
}
