CREATE TABLE [dbo].[Company] (
    [ID]                           INT          IDENTITY(1,1)  NOT NULL,
    [Name]                         NVARCHAR (200) UNIQUE NOT NULL,
    [EstablishDate]                DATE           NOT NULL,
    [CityId]                       INT            NOT NULL,
    [IndustryId]                   INT            NOT NULL,
    [IsActive]                     BIT            NOT NULL,
    [Town]                         NVARCHAR (50)  NOT NULL,
    [CompanyTypeId]                INT            NOT NULL,
    [Address]                      NVARCHAR (500) NOT NULL,
    [Email]                        NVARCHAR (255)  NOT NULL,
    [ZipCode]                      NVARCHAR (20)  NOT NULL,
    [Website]                      NVARCHAR (255) NOT NULL,
    [CommercialRegistrationNumber] NVARCHAR (30) UNIQUE NOT NULL,
    [TaxRegistrationNumber]        NVARCHAR (30) UNIQUE NOT NULL,
    [ParentId]                     INT            NULL,
    [LogoURL]                         NVARCHAR (255) NOT NULL,
       [Created]    DATETIME       NOT NULL,
    [CreatedBy]  INT  NOT NULL,
    [Updated]    DATETIME       NOT NULL,
    [UpdatedBy]  INT  NOT NULL,
    [RowVersion] TIMESTAMP NOT NULL,
    CONSTRAINT [PK__Company__3214EC27621FACBE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Company_City] FOREIGN KEY ([CityId]) REFERENCES [dbo].[City] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Company_Company] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Company] ([ID]),
    --CONSTRAINT [FK_Company_CompanyTelephoneNumber] FOREIGN KEY ([TelephoneNumberId]) REFERENCES [dbo].[CompanyTelephoneNumber] ([id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Company_CompanyType1] FOREIGN KEY ([CompanyTypeId]) REFERENCES [dbo].[CompanyType] ([ID]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Company_Industry] FOREIGN KEY ([IndustryId]) REFERENCES [dbo].[Industry] ([Id]) ON UPDATE CASCADE
);

