CREATE TABLE [dbo].[Employee] (
    [Id]                   INT          IDENTITY(1,1)  NOT NULL,
    [FirstName]            NVARCHAR (50)  NOT NULL,
    [MiddleName]           NVARCHAR (50)  NOT NULL,
    [LastName]             NVARCHAR (50)  NOT NULL,
    [CityId]               INT            NOT NULL,
    [Address]              NVARCHAR (500) NOT NULL,
    [JobTitleId]           INT            NOT NULL,
    [ManagerId]            INT            NULL,
    [GenderId]             INT            NOT NULL,
    [MilitaryStatusId]     INT            NULL,
    [BirthDate]            DATE           NOT NULL,
    [JobTypeId]            INT            NOT NULL,
    [JoiningDate]          DATE           NOT NULL,
    [EmploymentTypeId]           INT            NOT NULL,
    [WorkingModelId]       INT            NOT NULL,
    [IdentificationTypeId] INT            NOT NULL,
    [Identification]     INT            UNIQUE NOT NULL,
    [ExitDate]             DATE           NULL,
    [Email]                NVARCHAR (50) UNIQUE NOT NULL,
    [Salary]               INT            NOT NULL,
    [NationalityId]          INT  NOT NULL,
    [MedicalInsurance]     NVARCHAR (50) UNIQUE NULL,
    [MaritalStatusId]      INT            NOT NULL,
    [Created]    DATETIME       NOT NULL,
    [CreatedBy]  INT  NOT NULL,
    [Updated]    DATETIME       NOT NULL,
    [UpdatedBy]  INT  NOT NULL,
    [RowVersion] TIMESTAMP NOT NULL, 
    CONSTRAINT [PK__Employee__3214EC07F195CECB] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Employee_City] FOREIGN KEY ([CityId]) REFERENCES [dbo].[City] ([Id]),
    CONSTRAINT [FK_Employee_EmploymentType] FOREIGN KEY ([EmploymentTypeId]) REFERENCES [dbo].[EmploymentType] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Employee_Employee] FOREIGN KEY ([ManagerId]) REFERENCES [dbo].[Employee] ([Id]),
    CONSTRAINT [FK_Employee_Gender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[Gender] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Employee_Identification] FOREIGN KEY ([IdentificationTypeId]) REFERENCES [dbo].[IdentificationType] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Employee_JobTitle] FOREIGN KEY ([JobTitleId]) REFERENCES [dbo].[JobTitle] ([Id]),
    CONSTRAINT [FK_Employee_JobType] FOREIGN KEY ([JobTypeId]) REFERENCES [dbo].[JobType] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Employee_MatrialStatus] FOREIGN KEY ([MaritalStatusId]) REFERENCES [dbo].[MaritalStatus] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Employee_MilitaryStatus] FOREIGN KEY ([MilitaryStatusId]) REFERENCES [dbo].[MilitaryStatus] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Employee_WorkingModel] FOREIGN KEY ([WorkingModelId]) REFERENCES [dbo].[WorkingModel] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_Employee_Nationality] FOREIGN KEY ([NationalityId]) REFERENCES [dbo].[Country] ([ID]) ON UPDATE CASCADE
);

