CREATE TABLE [dbo].[HeadCountItem] (
    [Id]                       INT        IDENTITY(1,1)    NOT NULL,
    [HeadCountId]              INT            NOT NULL,
    [HeadCountTypeId]          INT            NOT NULL,
    [EmployeeId]               INT            NOT NULL,
    [GenderId]                 INT            NOT NULL,
    [FirstName]                NVARCHAR (50)  NOT NULL,
    [MiddleName]               NVARCHAR (50)  NOT NULL,
    [LastName]                 NVARCHAR (50)  NOT NULL,
    [BirthDate]                DATE           NOT NULL,
    [Address]                  NVARCHAR (500) NOT NULL,
    [DepartmentId]             INT            NOT NULL,
    [JobTitleId]               INT            NOT NULL,
    [ManagerId]                INT            NULL,
    [Salary]                   INT            NOT NULL,
    [MilitaryStatusId]         INT            NULL,
    [MaritalStatusId]          INT            NOT NULL,
    [JobTypeId]                INT            NOT NULL,
    [JoiningDate]              DATE           NOT NULL,
    [WorkingModelId]           INT            NOT NULL,
    [NationalityId]              INT  NOT NULL,
    [IdentificationTypeId]     INT            NOT NULL,
    [MedicalInsurance]         NVARCHAR (50)  NULL,
    [FromDepartmentJobTitleId] INT            NULL,
    [ToDepartmentJobTitleId]   INT            NULL,
    [FromWorkingModelId]       INT            NULL,
    [ToWorkingModelId]         INT            NULL,
    [ITCheckDate]              DATETIME       NULL,
    [ITCheckBy]                INT  NULL,
    [HRCheckDate] DATETIME NULL,
    [HRCheckBy] INT NULL,
    [Created]    DATETIME       NOT NULL,
    [CreatedBy]  INT  NOT NULL,
    [Updated]    DATETIME       NOT NULL,
    [UpdatedBy]  INT  NOT NULL,
    [RowVersion] TIMESTAMP NOT NULL, 

    CONSTRAINT [PK__HeadCoun__3214EC07F31532E4] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_HeadCountItem_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([Id]),
    CONSTRAINT [FK_HeadCountItem_FromDepartment] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [FK_HeadCountItem_FromWorkingModel] FOREIGN KEY ([WorkingModelId]) REFERENCES [dbo].[WorkingModel] ([Id]),
    CONSTRAINT [FK_HeadCountItem_Gender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[Gender] ([Id]),
    CONSTRAINT [FK_HeadCountItem_HeadCount] FOREIGN KEY ([HeadCountId]) REFERENCES [dbo].[HeadCount] ([Id]),
    CONSTRAINT [FK_HeadCountItem_HeadCountItem1] FOREIGN KEY ([JobTitleId]) REFERENCES [dbo].[JobTitle] ([Id]),
    CONSTRAINT [FK_HeadCountItem_HeadCountItem2] FOREIGN KEY ([IdentificationTypeId]) REFERENCES [dbo].[IdentificationType] ([Id]),
    CONSTRAINT [FK_HeadCountItem_HeadCountType] FOREIGN KEY ([HeadCountTypeId]) REFERENCES [dbo].[HeadCountType] ([Id]),
    CONSTRAINT [FK_HeadCountItem_JobType] FOREIGN KEY ([JobTypeId]) REFERENCES [dbo].[JobType] ([Id]),
    CONSTRAINT [FK_HeadCountItem_Manager] FOREIGN KEY ([ManagerId]) REFERENCES [dbo].[Employee] ([Id]),
    CONSTRAINT [FK_HeadCountItem_MaritalStatus] FOREIGN KEY ([MaritalStatusId]) REFERENCES [dbo].[MaritalStatus] ([Id]),
    CONSTRAINT [FK_HeadCountItem_MilitaryStatus] FOREIGN KEY ([MilitaryStatusId]) REFERENCES [dbo].[MilitaryStatus] ([Id]),
    CONSTRAINT [FK_HeadCountItem_ToDepartment] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [FK_HeadCountItem_ToWorkingModel] FOREIGN KEY ([WorkingModelId]) REFERENCES [dbo].[WorkingModel] ([Id]),
    CONSTRAINT [FK_HeadCountItem_Nationality] FOREIGN KEY ([WorkingModelId]) REFERENCES [dbo].[Country] ([ID])
);

