CREATE TABLE [dbo].[MaritalStatus] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Value] NVARCHAR (50) UNIQUE NOT NULL,
    CONSTRAINT [PK__MatrialS__3214EC0707AF5D45] PRIMARY KEY CLUSTERED ([Id] ASC)
);

