// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models;

[Table("Company")]
public partial class Company
{
    [Key]
    public int Id { get; set; }

    [StringLength(200)]
    public string Name { get; set; } = null!;

    public DateOnly EstablishDate { get; set; }

    public int CityId { get; set; }

    public int IndustryId { get; set; }

    public bool IsActive { get; set; }

    [StringLength(50)]
    public string Town { get; set; } = null!;

    public int CompanyTypeId { get; set; }

    [StringLength(200)]
    public string Address { get; set; } = null!;

    [StringLength(50)]
    public string Email { get; set; } = null!;

    [StringLength(20)]
    public string? ZipCode { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; } = null!;

    [StringLength(200)]
    public string Website { get; set; } = null!;

    [StringLength(50)]
    public string CommercialRegistrationNumber { get; set; } = null!;

    [StringLength(50)]
    public string TaxRegistrationNumber { get; set; } = null!;

    [StringLength(200)]
    public string Logo { get; set; } = null!;

    public DateTime Created { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; } = null!;

    public DateTime Updated { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; } = null!;

    public byte[] RowVersion { get; set; } = null!;
}