// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models;

[Table("HeadCountItem")]
public partial class HeadCountItem
{
    [Key]
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public int DepartmentId { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; } = null!;

    [StringLength(20)]
    public string MiddleName { get; set; } = null!;

    [StringLength(20)]
    public string LastName { get; set; } = null!;

    [StringLength(250)]
    public string Address { get; set; } = null!;

    public int GenderId { get; set; }

    public int MilitaryStatusId { get; set; }

    public int ManagerId { get; set; }

    public DateOnly BirthDate { get; set; }

    public int JobTypeId { get; set; }

    public DateOnly JoiningDate { get; set; }

    public int WorkingModelId { get; set; }

    public int JobTitleId { get; set; }

    public int IdentifactionTypeId { get; set; }

    public DateOnly ExitDate { get; set; }

    [StringLength(50)]
    public string Email { get; set; } = null!;

    public int Salary { get; set; }

    [StringLength(50)]
    public string Nationality { get; set; } = null!;

    [StringLength(50)]
    public string? MedicalInssurance { get; set; }

    public DateTime Created { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; } = null!;

    public DateTime Updated { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; } = null!;

    public byte[] RowVersion { get; set; } = null!;
}