// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Shared.Models;

[Table("Telephone Number")]
public partial class Telephone_Number
{
    [Key]
    public int Id { get; set; }

    public bool IsPrimary { get; set; }

    [StringLength(20)]
    public string Number { get; set; } = null!;

    public DateTime Created { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; } = null!;

    public DateTime Updated { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; } = null!;

    public byte[] RowVersion { get; set; } = null!;
}