// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("City")]
[Index("CountryId", Name = "IX_City_CountryId")]
public partial class City
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Display(Name = "Country")]
    public int CountryId { get; set; }

    [Display(Name = "Is Active?")]
    public bool IsActive { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    [ForeignKey("CountryId")]
    [InverseProperty("Cities")]
    public virtual Country Country { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}