// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Reflections.Nexus.WebUI.Code;

namespace Reflections.Nexus.WebUI.Models;

[Index("CompanyId", Name = "IX_CompanyFiles_CompanyId")]
[Index("FileTypeId", Name = "IX_CompanyFiles_FileTypeId")]
public partial class CompanyFile : BaseEntity
{
    [Display(Name = "File Type")]
    public int FileTypeId { get; set; }

    [Required]
    [Column("URL")]
    [StringLength(255)]
    public string Url { get; set; }
    [Display(Name = "Company")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("CompanyFiles")]
    public virtual Company Company { get; set; }

    [ForeignKey("FileTypeId")]
    [InverseProperty("CompanyFiles")]
    public virtual CompanyFileType FileType { get; set; }
}