// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("CompanyTelephoneNumber")]
[Index("CompanyId", Name = "IX_CompanyTelephoneNumber_CompanyId")]
[Index("TypeId", Name = "IX_CompanyTelephoneNumber_TypeId")]
public partial class CompanyTelephoneNumber
{
    [Key]
    public int Id { get; set; }


    public int CompanyId { get; set; }

    [Required]
    [StringLength(20)]
    public string PhoneNumber { get; set; }

    public int TypeId { get; set; }

    public bool IsPrimary { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("CompanyTelephoneNumbers")]
    public virtual Company Company { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("CompanyTelephoneNumbers")]
    public virtual PhoneNumberType Type { get; set; }
}