// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Reflections.Nexus.WebUI.Code;

namespace Reflections.Nexus.WebUI.Models;

[Table("Company")]
[Index("CountryId", Name = "IX_Company_CountryId")]
[Index("CityId", Name = "IX_Company_CityId")]
[Index("CompanyTypeId", Name = "IX_Company_CompanyType")]
[Index("IndustryId", Name = "IX_Company_IndustryId")]
[Index("ParentId", Name = "IX_Company_ParentId")]
public partial class Company : BaseEntity
{
    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [Column(TypeName = "date")]
    [Display(Name = "Date of Establishment")]
    public DateTime EstablishDate { get; set; }

    [Display(Name = "Country")]
    public int CountryId { get; set; }

    [Display(Name = "City")]
    public int CityId { get; set; }

    [Display(Name = "Industry")]
    public int IndustryId { get; set; }

    [Display(Name = "Is Active?")]
    public bool IsActive { get; set; }

    [Required]
    [StringLength(50)]
    public string Town { get; set; }

    [Display(Name = "Company")]
    public int CompanyTypeId { get; set; }

    [Required]
    [StringLength(500)]
    public string Address { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    public string ZipCode { get; set; }

    [Required]
    [StringLength(255)]
    public string Website { get; set; }

    [Required]
    [RegularExpression(@"^\d+$", ErrorMessage = "The Identification must be a valid integer.")]
    [Display(Name = "Commercial Registration Number")]
    public string CommercialRegistrationNumber { get; set; }

    [Required]
    [RegularExpression(@"^\d+$", ErrorMessage = "The Identification must be a valid integer.")]
    [Display(Name ="Tax Registration Number")]
    public string TaxRegistrationNumber { get; set; }

    [Display(Name = "Parent ID")]
    public int? ParentId { get; set; }

    [Required]
    [Column("LogoURL")]
    [StringLength(255)]
    public string LogoUrl { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("Companies")]
    public virtual City City { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<CompanyFile> CompanyFiles { get; set; } = new List<CompanyFile>();

    [InverseProperty("Company")]
    public virtual ICollection<CompanyTelephoneNumber> CompanyTelephoneNumbers { get; set; } = new List<CompanyTelephoneNumber>();

    [ForeignKey("CompanyTypeId")]
    [InverseProperty("Companies")]
    public virtual CompanyType CompanyType { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("IndustryId")]
    [InverseProperty("Companies")]
    public virtual Industry Industry { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<Company> InverseParent { get; set; } = new List<Company>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual Company Parent { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<SocialLink> SocialLinks { get; set; } = new List<SocialLink>();
}