// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("EmployeeRequest")]
[Index("EmployeeId", Name = "IX_EmployeeRequest_EmployeeId")]
[Index("NotificationId", Name = "IX_EmployeeRequest_NotificationId")]
[Index("StatusId", Name = "IX_EmployeeRequest_StatusId")]
public partial class EmployeeRequest
{
    [Key]
    public int Id { get; set; }

    [Display(Name = "Notification")]
    public int NotificationId { get; set; }

    [Display(Name = "Employee")]
    public int EmployeeId { get; set; }

    public int StatusId { get; set; }

    [Required]
    [Column(TypeName = "ntext")]
    public string Notes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeRequests")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("NotificationId")]
    [InverseProperty("EmployeeRequests")]
    public virtual Notification Notification { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("EmployeeRequests")]
    public virtual RequestStatus Status { get; set; }
}