// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("EmployeeTelephoneNumber")]
[Index("EmployeeId", Name = "IX_EmployeeTelephoneNumber_EmployeeId")]
[Index("TypeId", Name = "IX_EmployeeTelephoneNumber_TypeId")]
public partial class EmployeeTelephoneNumber
{
    [Key]
    public int Id { get; set; }

    [Display(Name = "Is Primary?")]
    public bool IsPrimary { get; set; }

    [Required]
    [StringLength(20)]
    public string Number { get; set; }

    [Display(Name = "Employee")]
    public int EmployeeId { get; set; }

    [Display(Name = "Type")]
    public int TypeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [Required]
    public byte[] RowVersion { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeTelephoneNumbers")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("EmployeeTelephoneNumbers")]
    public virtual PhoneNumberType Type { get; set; }
}