// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Reflections.Nexus.WebUI.Code;

namespace Reflections.Nexus.WebUI.Models;

[Table("Employee")]
[Index("CityId", Name = "IX_Employee_CityId")]
[Index("EmploymentTypeId", Name = "IX_Employee_EmploymentTypeId")]
[Index("GenderId", Name = "IX_Employee_GenderId")]
[Index("IdentificationTypeId", Name = "IX_Employee_IdentificationTypeId")]
[Index("JobTitleId", Name = "IX_Employee_JobTitleId")]
[Index("JobTypeId", Name = "IX_Employee_JobTypeId")]
[Index("ManagerId", Name = "IX_Employee_ManagerId")]
[Index("MaritalStatusId", Name = "IX_Employee_MaritalStatusId")]
[Index("MilitaryStatusId", Name = "IX_Employee_MilitaryStatusId")]
[Index("NationalityId", Name = "IX_Employee_NationalityId")]
[Index("WorkingModelId", Name = "IX_Employee_WorkingModelId")]
public partial class Employee : BaseEntity
{
   
    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string MiddleName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    public string FullName => $"{FirstName} {MiddleName} {LastName}";

    public int CityId { get; set; }

    [Required]
    [StringLength(500)]
    public string Address { get; set; }

    public int JobTitleId { get; set; }

    public int? ManagerId { get; set; }

    public int GenderId { get; set; }

    public int? MilitaryStatusId { get; set; }

    [Column(TypeName = "date")]
    public DateTime BirthDate { get; set; }

    public int JobTypeId { get; set; }

    [Column(TypeName = "date")]
    public DateTime JoiningDate { get; set; }

    public int EmploymentTypeId { get; set; }

    public int WorkingModelId { get; set; }

    public int IdentificationTypeId { get; set; }

    public string Identification { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ExitDate { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    public int Salary { get; set; }

    public int NationalityId { get; set; }

    [StringLength(50)]
    public string MedicalInsurance { get; set; }

    public int MaritalStatusId { get; set; }


    [ForeignKey("CityId")]
    [InverseProperty("Employees")]
    public virtual City City { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeeFile> EmployeeFiles { get; set; } = new List<EmployeeFile>();

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeeRequest> EmployeeRequests { get; set; } = new List<EmployeeRequest>();

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeeTelephoneNumber> EmployeeTelephoneNumbers { get; set; } = new List<EmployeeTelephoneNumber>();

    [ForeignKey("EmploymentTypeId")]
    [InverseProperty("Employees")]
    public virtual EmploymentType EmploymentType { get; set; }

    [ForeignKey("GenderId")]
    [InverseProperty("Employees")]
    public virtual Gender Gender { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<HeadCountItem> HeadCountItemEmployees { get; set; } = new List<HeadCountItem>();

    [InverseProperty("Manager")]
    public virtual ICollection<HeadCountItem> HeadCountItemManagers { get; set; } = new List<HeadCountItem>();

    [ForeignKey("IdentificationTypeId")]
    [InverseProperty("Employees")]
    public virtual IdentificationType IdentificationType { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Employee> InverseManager { get; set; } = new List<Employee>();

    [ForeignKey("JobTitleId")]
    [InverseProperty("Employees")]
    public virtual JobTitle JobTitle { get; set; }

    [ForeignKey("JobTypeId")]
    [InverseProperty("Employees")]
    public virtual JobType JobType { get; set; }

    [ForeignKey("ManagerId")]
    [InverseProperty("InverseManager")]
    public virtual Employee Manager { get; set; }

    [ForeignKey("MaritalStatusId")]
    [InverseProperty("Employees")]
    public virtual MaritalStatus MaritalStatus { get; set; }

    [ForeignKey("MilitaryStatusId")]
    [InverseProperty("Employees")]
    public virtual MilitaryStatus MilitaryStatus { get; set; }

    [ForeignKey("NationalityId")]
    [InverseProperty("Employees")]
    public virtual Country Nationality { get; set; }

    [ForeignKey("WorkingModelId")]
    [InverseProperty("Employees")]
    public virtual WorkingModel WorkingModel { get; set; }
}