// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("Gender")]
public partial class Gender
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(6)]
    public string Value { get; set; }

    [InverseProperty("Gender")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [InverseProperty("Gender")]
    public virtual ICollection<HeadCountItem> HeadCountItems { get; set; } = new List<HeadCountItem>();
}