// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Reflections.Nexus.WebUI.Code;

namespace Reflections.Nexus.WebUI.Models;

[Table("JobTitle")]
[Index("DepartmentId", Name = "IX_JobTitle_DepartmentId")]
public partial class JobTitle
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Display(Name = "Department")]
    public int DepartmentId { get; set; }

    [Display(Name = "Is Active?")]
    public bool IsActive { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("JobTitles")]
    public virtual Department Department { get; set; }

    [InverseProperty("JobTitle")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [InverseProperty("FromDepartmentJobTitle")]
    public virtual ICollection<HeadCountItem> HeadCountItemFromDepartmentJobTitles { get; set; } = new List<HeadCountItem>();

    [InverseProperty("ToDepartmentJobTitle")]
    public virtual ICollection<HeadCountItem> HeadCountItemToDepartmentJobTitles { get; set; } = new List<HeadCountItem>();
}