// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("PhoneNumberType")]
public partial class PhoneNumberType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(30)]
    public string Value { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<CompanyTelephoneNumber> CompanyTelephoneNumbers { get; set; } = new List<CompanyTelephoneNumber>();

    [InverseProperty("Type")]
    public virtual ICollection<EmployeeTelephoneNumber> EmployeeTelephoneNumbers { get; set; } = new List<EmployeeTelephoneNumber>();
}