// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("RequestStatus")]
public partial class RequestStatus
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string Value { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<EmployeeRequest> EmployeeRequests { get; set; } = new List<EmployeeRequest>();
}