// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Index("CompanyId", Name = "IX_SocialLinks_CompanyId")]
[Index("SocialTypeId", Name = "IX_SocialLinks_SocialTypeId")]
public partial class SocialLink
{
    [Key]
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int SocialTypeId { get; set; }

    [Required]
    [StringLength(255)]
    public string Url { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("SocialLinks")]
    public virtual Company Company { get; set; }

    [ForeignKey("SocialTypeId")]
    [InverseProperty("SocialLinks")]
    public virtual SocialLinkType SocialType { get; set; }
}