// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.WebUI.Models;

[Table("WorkingModel")]
public partial class WorkingModel
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Value { get; set; }

    [InverseProperty("WorkingModel")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [InverseProperty("FromWorkingModel")]
    public virtual ICollection<HeadCountItem> HeadCountItemFromWorkingModels { get; set; } = new List<HeadCountItem>();

    [InverseProperty("ToWorkingModel")]
    public virtual ICollection<HeadCountItem> HeadCountItemToWorkingModels { get; set; } = new List<HeadCountItem>();
}