// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class CompanyFiles
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string File_Name { get; set; }

    public int File_type_id { get; set; }

    [Required]
    [StringLength(50)]
    public string file_url { get; set; }

    public int Company_Id { get; set; }

    [ForeignKey("Company_Id")]
    [InverseProperty("Company_Files")]
    public virtual Company Company { get; set; }

    [ForeignKey("File_type_id")]
    [InverseProperty("Company_Files")]
    public virtual FileType File_type { get; set; }
}