// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class Company
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string Addresse { get; set; }

    [Required]
    [StringLength(50)]
    public string WebSite { get; set; }

    [Required]
    [StringLength(50)]
    public string Logo_Url { get; set; }

    public int Social_Number { get; set; }

    [Required]
    [StringLength(50)]
    public string Company_Type { get; set; }

    public int Tax_Card_Number { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<CompanyFiles> Company_Files { get; set; } = new List<CompanyFiles>();
}