// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class Department
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int Manager_Id { get; set; }

    [InverseProperty("Dep")]
    public virtual ICollection<Employees> Employees { get; set; } = new List<Employees>();

    [InverseProperty("Dep")]
    public virtual ICollection<JopTitle> Jop_Title { get; set; } = new List<JopTitle>();

    [ForeignKey("Manager_Id")]
    [InverseProperty("Department")]
    public virtual Employees Manager { get; set; }
}