// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class Employees
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    public int Dep_Id { get; set; }

    public int Jop_Title_Id { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal Salary { get; set; }

    public int National_Id { get; set; }

    [Column("B.O.D")]
    public DateOnly B_O_D { get; set; }

    [Required]
    [StringLength(50)]
    public string Nationality { get; set; }

    [Required]
    [StringLength(50)]
    public string Military_Status { get; set; }

    [Required]
    [StringLength(50)]
    public string Martial_Status { get; set; }

    public int Gender_Id { get; set; }

    public int Social_Insurance_Id { get; set; }

    public int Medical_Insurance_Id { get; set; }

    public int User_Id { get; set; }

    public DateOnly Hire_Date { get; set; }

    public int Direct_Manager_Id { get; set; }

    public int Country_Id { get; set; }

    public int City_Id { get; set; }

    [ForeignKey("City_Id")]
    [InverseProperty("Employees")]
    public virtual City City { get; set; }

    [ForeignKey("Country_Id")]
    [InverseProperty("Employees")]
    public virtual Country Country { get; set; }

    [ForeignKey("Dep_Id")]
    [InverseProperty("Employees")]
    public virtual Department Dep { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Department> Department { get; set; } = new List<Department>();

    [ForeignKey("Direct_Manager_Id")]
    [InverseProperty("InverseDirect_Manager")]
    public virtual Employees Direct_Manager { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeesFiles> Employees_Files { get; set; } = new List<EmployeesFiles>();

    [ForeignKey("Gender_Id")]
    [InverseProperty("Employees")]
    public virtual Gender Gender { get; set; }

    [InverseProperty("Emp")]
    public virtual ICollection<Headcount> Head_countEmp { get; set; } = new List<Headcount>();

    [InverseProperty("From_direct_manager")]
    public virtual ICollection<Headcount> Head_countFrom_direct_manager { get; set; } = new List<Headcount>();

    [InverseProperty("To_direct_manager")]
    public virtual ICollection<Headcount> Head_countTo_direct_manager { get; set; } = new List<Headcount>();

    [InverseProperty("Direct_Manager")]
    public virtual ICollection<Employees> InverseDirect_Manager { get; set; } = new List<Employees>();

    [ForeignKey("Jop_Title_Id")]
    [InverseProperty("Employees")]
    public virtual JopTitle Jop_Title { get; set; }

    [ForeignKey("User_Id")]
    [InverseProperty("Employees")]
    public virtual Users User { get; set; }
}