// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class EmployeesFiles
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string File_Name { get; set; }

    public int File_Type_Id { get; set; }

    [Required]
    [StringLength(50)]
    public string File_Url { get; set; }

    public int Employee_Id { get; set; }

    [ForeignKey("Employee_Id")]
    [InverseProperty("Employees_Files")]
    public virtual Employees Employee { get; set; }

    [ForeignKey("File_Type_Id")]
    [InverseProperty("Employees_Files")]
    public virtual FileType File_Type { get; set; }
}