// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class FileType
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("File_type")]
    public virtual ICollection<CompanyFiles> Company_Files { get; set; } = new List<CompanyFiles>();

    [InverseProperty("File_Type")]
    public virtual ICollection<EmployeesFiles> Employees_Files { get; set; } = new List<EmployeesFiles>();
}