// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class Headcount
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Note { get; set; }

    public bool Activated { get; set; }

    public DateOnly End_Date { get; set; }

    public int Emp_id { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal salary { get; set; }

    public int Type_id { get; set; }

    public DateOnly Activated_date { get; set; }

    public int From_jop_title_id { get; set; }

    public int To_jop_title_id { get; set; }

    public int User_id { get; set; }

    public int Private_id { get; set; }

    [Required]
    [StringLength(50)]
    public string English_name { get; set; }

    [Required]
    [StringLength(50)]
    public string Arabic_name { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    public DateOnly From_date { get; set; }

    public DateOnly To_date { get; set; }

    public int From_direct_manager_id { get; set; }

    public int To_direct_manager_id { get; set; }

    public int From_Working_model_id { get; set; }

    public int To_Working_model_id { get; set; }

    public bool Hr_finger_print_checked { get; set; }

    [Required]
    [StringLength(50)]
    public string Hr_finger_print_checked_by { get; set; }

    public bool It_email_checked { get; set; }

    [Required]
    [StringLength(50)]
    public string It_email_checked_by { get; set; }

    public bool Hr_Sm_card_checked { get; set; }

    [Required]
    [StringLength(50)]
    public string Hr_sm_card_checked_by { get; set; }

    public int Gender_id { get; set; }

    public int Contracting_status_id { get; set; }

    [Required]
    [StringLength(50)]
    public string Payroll { get; set; }

    [ForeignKey("Contracting_status_id")]
    [InverseProperty("Head_count")]
    public virtual ContractingStatus Contracting_status { get; set; }

    [ForeignKey("Emp_id")]
    [InverseProperty("Head_countEmp")]
    public virtual Employees Emp { get; set; }

    [ForeignKey("From_Working_model_id")]
    [InverseProperty("Head_countFrom_Working_model")]
    public virtual WorkingModel From_Working_model { get; set; }

    [ForeignKey("From_direct_manager_id")]
    [InverseProperty("Head_countFrom_direct_manager")]
    public virtual Employees From_direct_manager { get; set; }

    [ForeignKey("From_jop_title_id")]
    [InverseProperty("Head_countFrom_jop_title")]
    public virtual JopTitle From_jop_title { get; set; }

    [ForeignKey("Gender_id")]
    [InverseProperty("Head_count")]
    public virtual Gender Gender { get; set; }

    [ForeignKey("To_Working_model_id")]
    [InverseProperty("Head_countTo_Working_model")]
    public virtual WorkingModel To_Working_model { get; set; }

    [ForeignKey("To_direct_manager_id")]
    [InverseProperty("Head_countTo_direct_manager")]
    public virtual Employees To_direct_manager { get; set; }

    [ForeignKey("To_jop_title_id")]
    [InverseProperty("Head_countTo_jop_title")]
    public virtual JopTitle To_jop_title { get; set; }

    [ForeignKey("Type_id")]
    [InverseProperty("Head_count")]
    public virtual HeadCountType Type { get; set; }

    [ForeignKey("User_id")]
    [InverseProperty("Head_count")]
    public virtual Users User { get; set; }
}