// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class JopTitle
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int Dep_Id { get; set; }

    [ForeignKey("Dep_Id")]
    [InverseProperty("Jop_Title")]
    public virtual Department Dep { get; set; }

    [InverseProperty("Jop_Title")]
    public virtual ICollection<Employees> Employees { get; set; } = new List<Employees>();

    [InverseProperty("From_jop_title")]
    public virtual ICollection<Headcount> Head_countFrom_jop_title { get; set; } = new List<Headcount>();

    [InverseProperty("To_jop_title")]
    public virtual ICollection<Headcount> Head_countTo_jop_title { get; set; } = new List<Headcount>();
}