// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class Users
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Name { get; set; }

    public int Password { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Employees> Employees { get; set; } = new List<Employees>();

    [InverseProperty("User")]
    public virtual ICollection<Headcount> Head_count { get; set; } = new List<Headcount>();
}