// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reflections.Nexus.Models;

public partial class WorkingModel
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("From_Working_model")]
    public virtual ICollection<Headcount> Head_countFrom_Working_model { get; set; } = new List<Headcount>();

    [InverseProperty("To_Working_model")]
    public virtual ICollection<Headcount> Head_countTo_Working_model { get; set; } = new List<Headcount>();
}